server:
    servlet:
         context-path: "/benchmark"
    port: 8085

spring:
    data:
        mongodb:
            uri         : "mongodb://localhost:27017"
            database    : "mega"

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details : "always"